networks:
  red_usuarios:
    driver: bridge
    name: chemait_red_usuarios
    ipam:
      config:
        - subnet: 172.172.10.0/24
          gateway: 172.172.10.1
  red_servidores:
    driver: bridge
    name: chemait_red_servidores
    ipam:
      config:
        - subnet: 172.172.20.0/24
          gateway: 172.172.20.1
  red_dmz:
    driver: bridge
    name: chemait_red_dmz
    ipam:
      config:
        - subnet: 172.172.30.0/24
          gateway: 172.172.30.1
  red_admin:
    driver: bridge
    name: chemait_red_admin
    ipam:
      config:
        - subnet: 172.172.40.0/24
          gateway: 172.172.40.1
  red_impresion:
    driver: bridge
    name: chemait_red_impresion
    ipam:
      config:
        - subnet: 172.172.50.0/24
          gateway: 172.172.50.1

services:

  servicios_internos:
    depends_on:
      firewall:
        condition: service_healthy
    image: ubuntu:latest
    container_name: servicios_internos
    privileged: true
    networks:
      red_servidores:
        ipv4_address: 172.172.20.10
    command: >
      bash -c "apt update &&
               apt install -y net-tools iputils-ping curl iproute2 &&
               bash /routes/red_servidores_routes.sh && chmod +x /utilities/dockerInstaller.sh && /utilities/dockerInstaller.sh && tail -f /dev/null"
    volumes:
      - ./Servicios-internos:/setup
      - docker-interno:/var/lib/docker
      - ./routes:/routes:ro
      - ./utilities:/utilities
    restart: always

  servidor_backup:
    depends_on:
      firewall:
        condition: service_healthy
    image: ubuntu:latest
    container_name: servidor_backup
    privileged: true
    networks:
      red_servidores:
        ipv4_address: 172.172.20.20
    command: >
      bash -c "apt update &&
               apt install -y rsync net-tools iputils-ping curl iproute2 &&
               bash /routes/red_servidores_routes.sh && chmod +x /utilities/dockerInstaller.sh && /utilities/dockerInstaller.sh &&
               tail -f /dev/null"
    volumes:
      - ./servidor-backup:/setup
      - docker-interno:/var/lib/docker
      - ./routes:/routes:ro
      - ./utilities:/utilities
    restart: always

  servicios_externos:
    depends_on:
      firewall:
        condition: service_healthy
    image: ubuntu:latest
    container_name: servicios_externos
    privileged: true
    networks:
      red_dmz:
        ipv4_address: 172.172.30.10
    command: >
      bash -c "apt update &&
               apt install -y net-tools iputils-ping curl iproute2 &&
               bash /routes/red_dmz_routes.sh && chmod +x /utilities/dockerInstaller.sh && /utilities/dockerInstaller.sh && tail -f /dev/null "
    volumes:
      - ./Servicios-externos:/setup
      - docker-externo:/var/lib/docker
      - ./routes:/routes:ro
      - ./utilities:/utilities
    ports:
      - "80:80"
    restart: always

  cliente:
    depends_on:
      firewall:
        condition: service_healthy
    image: ubuntu:latest
    container_name: cliente
    privileged: true
    networks:
      red_usuarios:
        ipv4_address: 172.172.10.10
    command: >
      bash -c "apt update &&
               apt install -y net-tools iputils-ping curl iproute2 &&
               bash /routes/red_usuarios_routes.sh && chmod +x /utilities/dockerInstaller.sh && /utilities/dockerInstaller.sh &&
               tail -f /dev/null"
    volumes:
      - ./Usuarios-internos:/setup
      - ./routes:/routes:ro
      - ./utilities:/utilities
    restart: always

  admin_test:
    depends_on:
      firewall:
          condition: service_healthy
    image: ubuntu:latest
    container_name: admin_test
    privileged: true
    networks:
      red_admin:
        ipv4_address: 172.172.40.20
    command: >
      bash -c "apt update &&
               apt install -y net-tools iputils-ping curl htop iproute2 &&
               bash /routes/red_admin_routes.sh && chmod +x /utilities/dockerInstaller.sh && /utilities/dockerInstaller.sh &&
               tail -f /dev/null"
    volumes:
      - ./routes:/routes:ro
      - ./utilities:/utilities
    restart: always

  firewall:
    image: ubuntu:latest
    container_name: firewall
    privileged: true
    networks:
      red_usuarios:
        ipv4_address: 172.172.10.2
      red_servidores:
        ipv4_address: 172.172.20.2
      red_dmz:
        ipv4_address: 172.172.30.2
      red_admin:
        ipv4_address: 172.172.40.2
      red_impresion:
        ipv4_address: 172.172.50.2
    
    command: >
      bash -c "apt update && apt install -y iptables iproute2 net-tools iputils-ping curl tcpdump && sysctl -w net.ipv4.ip_forward=1 && echo 'net.ipv4.ip_forward=1' >> /etc/sysctl.conf && bash /routes/firewall_rules.sh && tail -f /dev/null && sleep infinity"
    
    restart: always
    volumes:
      - ./routes:/routes:ro
      - ./LOGS:/LOGS
      - ./utilities:/utilities
    healthcheck:
      test: ["CMD-SHELL", "chmod +x /utilities/healthcheck.sh && /utilities/healthcheck.sh"]
      interval: 10s
      timeout: 10s
      retries: 30
  impresora_1:
    depends_on:
      firewall:
          condition: service_healthy
    image: ubuntu:latest
    container_name: impresora_1
    privileged: true
    command: >
      bash -c "apt update &&
               apt install -y rsync net-tools iputils-ping curl iproute2 &&
               bash /routes/red_impresion_routes.sh &&
               tail -f /dev/null"
    volumes:
      - ./routes:/routes:ro
    networks:
      red_impresion:
        ipv4_address: 172.172.50.3
  impresora_2:
    depends_on:
      firewall:
          condition: service_healthy
    image: ubuntu:latest
    container_name: impresora_2
    privileged: true
    command: >
      bash -c "apt update &&
               apt install -y rsync net-tools iputils-ping curl iproute2 &&
               bash /routes/red_impresion_routes.sh && tail -f /dev/null"
    volumes:
      - ./routes:/routes:ro
    networks:
      red_impresion:
        ipv4_address: 172.172.50.4

volumes:
  docker-interno:
  docker-externo:
