services:
  emailRelleno:
    image: juanluisbaptiste/postfix:latest
    container_name: correo
    ports:
      - "587:587"
    restart: always
    environment:
      SMTP_SERVER: nteum.com        # Replace with your actual SMTP server
      SMTP_PORT: 588                       # Optional, can be omitted if 587
      SMTP_USERNAME: eneto         # Optional, set if authentication is needed
      SMTP_PASSWORD: eneto        # Mandatory if SMTP_USERNAME is set
      SERVER_HOSTNAME: nteum.com # Replace with your mail domain
  