
services:
  email:
    image: juanluisbaptiste/postfix:latest
    container_name: correo
    ports:
      - "587:587"
    restart: always
    environment:
      SMTP_SERVER: nteum.com        # Replace with your actual SMTP server
      SMTP_PORT: 587                       # Optional, can be omitted if 587
      SMTP_USERNAME: eneto         # Optional, set if authentication is needed
      SMTP_PASSWORD: eneto        # Mandatory if SMTP_USERNAME is set
      SERVER_HOSTNAME: nteum.com # Replace with your mail domain
  
######################################################################

  acceso-unico:
    image: osixia/openldap:latest
    container_name: acceso-unico
    ports:
      - "0.0.0.0:389:389"
      - "0.0.0.0:636:636"
    environment:
      LDAP_ORGANISATION: "NtEum S.A."
      LDAP_DOMAIN: "nteum.local"
      LDAP_ADMIN_PASSWORD: "eneto"
      LDAP_CONFIG_PASSWORD: "eneto"
      LDAP_TLS: "false"
    volumes:
      - ./local/acceso-unico/data:/var/lib/ldap        
      - ./local/acceso-unico/config:/etc/ldap/slapd.d

    restart: always



  datos-compartidos-windows:
    image: dperson/samba
    container_name: datos-compartidos-windows
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "1445:445/tcp"
    volumes:
      - ./local/datos-compartidos-windows:/mount
    command:
      - -u
      - "eneto;eneto"
      - -s
      - "public;/mount;yes;no;no;eneto"
      - -w
      - "WORKGROUP"
    restart: always






  impresion-red:
    image: olbat/cupsd:latest
    container_name: impresion-red
    ports:
      - "631:631"
    environment:
      - CUPS_USER_ADMIN=eneto
      - CUPS_USER_PASSWORD=eneto
    volumes:
      - ./local/impresion-red/config:/etc/cups
      - ./local/impresion-red/data:/var/spool/cups
    restart: always



  servidor-web:
    image: nginx:latest
    container_name: servidor-web
    ports:
      - "80:80"
    volumes:
      - ./local/servidor-web/www:/usr/share/nginx/html:ro
    restart: always



  base-datos:
    image: mysql:latest
    container_name: base-datos
    environment:
      MYSQL_ROOT_PASSWORD: eneto
      MYSQL_USER: eneto
      MYSQL_PASSWORD: eneto
      MYSQL_DATABASE: app_db
    ports:
      - "3306:3306"
    volumes:
      - ./local/base-datos/data:/var/lib/mysql
    restart: always




  libreoffice:
    image: linuxserver/libreoffice:latest
    container_name: libreoffice
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Mexico_City
    ports:
      - "3000:3000"
    volumes:
      - ./local/libreoffice/config:/config
      - ./local/libreoffice/documentos:/documents
    restart: unless-stopped


