
services:
  email:
    image: juanluisbaptiste/postfix:latest
    container_name: correo
    ports:
      - "587:587"
    restart: always
    environment:
      SMTP_SERVER: nteum.com        # Replace with your actual SMTP server
      SMTP_PORT: 587                       # Optional, can be omitted if 587
      SMTP_USERNAME: eneto         # Optional, set if authentication is needed
      SMTP_PASSWORD: eneto        # Mandatory if SMTP_USERNAME is set
      SERVER_HOSTNAME: nteum.com # Replace with your mail domain
  
######################################################################

  acceso-unico:
    image: osixia/openldap:latest
    container_name: acceso-unico
    ports:
      - "389:389"
      - "636:636"
    environment:
      LDAP_ORGANISATION: "NtEum S.A."
      LDAP_DOMAIN: "nteum.local"
      LDAP_ADMIN_PASSWORD: "agba"
      LDAP_CONFIG_PASSWORD: "agba"
      LDAP_TLS: "true"
      LDAP_TLS_CRT_FILENAME: "ldap.crt"
      LDAP_TLS_KEY_FILENAME: "ldap.key"
    volumes:
      - ./ldap/config:/container/service/slapd/assets/config
      - ./ldap/certs:/container/service/slapd/assets/certs
      - ./ldap/data:/var/lib/ldap
    restart: always



  datos-compartidos-windows:
    image: dperson/samba
    container_name: datos-compartidos-windows
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    volumes:
      - ./compartido:/mount
    command: >
      -u "agba;agba"
      -s "public;/mount;yes;no;no;agba"
    restart: always



  impresion-red:
    image: olbat/cupsd:latest
    container_name: impresion-red
    ports:
      - "631:631"
    volumes:
      - ./config/cups:/etc/cups
      - ./data/cups:/var/spool/cups
    restart: always



  servidor-web:
    image: nginx:latest
    container_name: servidor-web
    ports:
      - "80:80"
    volumes:
      - ./www:/usr/share/nginx/html:ro
    restart: always



  base-datos:
    image: mysql:latest
    container_name: base-datos
    environment:
      MYSQL_USER: eneto
      MYSQL_PASSWORD: eneto
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    restart: always



  # libreoffice:
  #   image: libreoffice/docker-libreoffice
  #   container_name: libreoffice
  #   command: soffice --headless --accept="socket,host=0.0.0.0,port=8100;urp;" --nofirststartwizard
  #   ports:
  #     - "8100:8100"
  #   restart: unless-stopped
