version: "3.9"

services:
  servidor_backup:
    image: alpinelinux/rsyncd:latest
    container_name: servidor_backup
    ports:
      - "873:873"
    volumes:
      - ./respaldo:/data
    restart: always
    environment:
      RSYNC_USERNAME: backupuser
      RSYNC_PASSWORD: secret123
      RSYNC_MODULES: respaldo
      RSYNC_MODULE_respaldo_comment: "Carpeta de respaldo"
      RSYNC_MODULE_respaldo_path: /data
      RSYNC_MODULE_respaldo_read_only: "false"
    networks:
      red_servidores:
        ipv4_address: 172.25.0.10

networks:
  red_servidores:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24
