services:
  servidor_backup:
    image: alpinelinux/rsyncd:latest
    container_name: servidor_backup
    ports:
      - "873:873"
    volumes:
      - ./respaldo:/data
    restart: always
    environment:
      RSYNC_USERNAME: backupuser
      RSYNC_PASSWORD: secret123
      RSYNC_MODULES: respaldo
      RSYNC_MODULE_respaldo_comment: "Carpeta de respaldo"
      RSYNC_MODULE_respaldo_path: /data
      RSYNC_MODULE_respaldo_read_only: "false"
      RSYNC_LOGFILE: /var/log/rsyncd.log
    networks:
      red_servidores:
        ipv4_address: 172.172.20.20
