version: '3.9'

services:
  servidor_backup:
    image: alpine:latest
    container_name: servidor_backup
    ports:
      - "873:873"
    volumes:
      - ./respaldo:/data
      - ./local/acceso-unico:/mnt/acceso-unico:ro
      - ./local/datos-compartidos-windows:/mnt/datos-compartidos-windows:ro
      - ./local/impresion-red:/mnt/impresion-red:ro
      - ./local/servidor-web:/mnt/servidor-web:ro
      - ./local/base-datos/data:/mnt/base-datos:ro
      - ./local/libreoffice/documentos:/mnt/libreoffice:ro
    command: >
      sh -c "
        apk add --no-cache rsync &&
        adduser -D backupuser &&
        echo 'backupuser:secret123' > /etc/rsyncd.secrets &&
        chmod 600 /etc/rsyncd.secrets &&
        echo '
        uid = backupuser
        gid = backupuser
        use chroot = no
        max connections = 2
        log file = /var/log/rsyncd.log
        timeout = 300
        auth users = backupuser
        secrets file = /etc/rsyncd.secrets

        [respaldo]
          path = /data
          comment = Carpeta de respaldo
          read only = no
          list = yes
        ' > /etc/rsyncd.conf &&
        rsync --daemon --no-detach
      "
    restart: always
