version: "3.9"

services:
  servidor_backup:
    image: alpine:latest
    container_name: servidor_backup
    ports:
      - "873:873"
    volumes:
      - /setup/local/respaldo:/data
    networks:
      red_servidores:
        ipv4_address: 172.172.20.20
    restart: always
    command: >
      sh -c "
        apk add --no-cache rsync &&
        adduser -D backupuser &&
        echo 'backupuser:secret123' > /etc/rsyncd.secrets &&
        chmod 600 /etc/rsyncd.secrets &&
        echo '
        uid = backupuser
        gid = backupuser
        use chroot = no
        max connections = 2
        log file = /var/log/rsyncd.log
        timeout = 300
        auth users = backupuser
        secrets file = /etc/rsyncd.secrets

        [respaldo]
          path = /data
          comment = Carpeta de respaldo
          read only = no
          list = yes
        ' > /etc/rsyncd.conf &&
        rsync --daemon --no-detach
      "

networks:
  red_servidores:
    external: true
    name: chemait_red_servidores
